/*
 * NullMoth NVIDIA driver for macOS
 * Copyright (c) 2026 NullMoth Systems.
 * SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
 */

#ifndef NVMTL_SAMPLE_DEPTH_CONTRACT_H
#define NVMTL_SAMPLE_DEPTH_CONTRACT_H
#define NVMTL_SAMPLE_DEPTH_INDEPENDENT_VALUES 0x1u
#define NVMTL_SAMPLE_DEPTH_UNCOMPRESSED_PLANES 0x2u
#define NVMTL_SAMPLE_DEPTH_LOCATION_INDEPENDENT_LAYOUT 0x4u
#define NVMTL_SAMPLE_DEPTH_NON_DISCARDING_LAYOUT_TRANSITIONS 0x8u
#define NVMTL_SAMPLE_DEPTH_CONTRACT_REQUIRED 0xfu
#endif
