#!/usr/bin/env python3
"""gen_tahoe_fwd.py NVACCEL_BINARY MISSING_SYMBOLS — writes tahoe_fwd.h for the macOS 26 build.

Tahoe (26) made 27 IOAcceleratorFamily2 methods private and retyped 7 more (unsigned int -> enum), so a kext can no longer
link to them by name. NVAccel never calls them: they only fill vtable slots our classes inherit. The vtable layout itself
is unchanged (every base vtable has the same slot count and order as on macOS 15; checked with tools/vtdump.py against the
26.7.1 KDK), and Apple still exports every base vtable. So for the 26 build each such slot gets an override that jumps
through the base class's exported vtable, which reaches Apple's implementation without naming it."""
import re, subprocess, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..', 'tools'))
from vtdump import vtables
HERE = os.path.dirname(os.path.abspath(__file__))
BASES = {'NVResource': 'IOAccelResource2', 'NVSysMemory': 'IOAccelSysMemory', 'NVVidMemory': 'IOAccelVidMemory',
         'NVSurface': 'IOAccelLegacySurface', 'NVDisplayPipe': 'IOAccelLegacyDisplayPipe', 'NVGLContext': 'IOAccelGLContext2',
         'NV2DContext': 'IOAccel2DContext2', 'NVCLContext': 'IOAccelCLContext2', 'NVVideoContext': 'IOAccelVideoContext2',
         'NVEventMachine': 'IOAccelEventMachineFast2', 'NVDisplayMachine': 'IOAccelLegacyDisplayMachine', 'NVTask': 'IOAccelTask',
         'NVMemoryMap': 'IOAccelMemoryMap', 'NVAccel': 'IOGraphicsAccelerator2'}
def decls():
    out = {}
    for sub in ('iofam', 're'):
      for f in os.listdir(os.path.join(HERE, sub)):
        if not f.endswith('.h'): continue
        cls = f[:-2]
        for l in open(os.path.join(HERE, sub, f)):
            m = re.match(r'\s*virtual\s+(.+?)\s+([A-Za-z_]\w*)\((.*?)\)(\s*const)?\s*(= 0)?\s*(APPLE_KEXT_OVERRIDE)?\s*;', l)
            if m:
                args = [a.strip() for a in m.group(3).split(',')] if m.group(3).strip() else []
                out.setdefault((cls, m.group(2), len(args), bool(m.group(4))), (m.group(1).strip(), args))
    return out
def main(binary, missfile):
    miss = {l.strip() for l in open(missfile) if l.strip()}
    vt = vtables(binary); d = decls()
    dem = lambda xs: subprocess.run(['c++filt'], input='\n'.join(xs), capture_output=True, text=True).stdout.split('\n')
    h = ['// GENERATED by gen_tahoe_fwd.py for the macOS 26 (Tahoe) build. Do not edit.', '#pragma once', '#ifdef NM_TAHOE']
    defs = []; used = set(); n = 0
    for cls, base in BASES.items():
        slots = vt['%d%s' % (len(cls), cls)]
        decl_lines = []
        for idx, (sym, dn) in enumerate(zip(slots, dem(slots))):
            if sym not in miss: continue
            m = re.match(r'(\w+)::(\w+)\((.*)\)( const)?$', dn)
            owner, name, const = m.group(1), m.group(2), bool(m.group(4))
            arity = 0 if not m.group(3).strip() else m.group(3).count(',') + 1
            ret, args = d[(owner, name, arity, const)]
            params = ', '.join('%s a%d' % (a, i) for i, a in enumerate(args))
            types = ''.join(', ' + a for a in args); call = ''.join(', a%d' % i for i in range(arity))
            c = ' const' if const else ''
            decl_lines.append('    %s %s(%s)%s override;' % (ret, name, params, c))
            # The vtable address is loaded through the GOT: ld -kext leaves a RIP-relative lea to an undefined symbol with no
            # relocation at all (measured: it pointed at 0), while GOT entries get UNSIGNED relocations the kernel linker fills.
            # A naked tail jump through the base vtable slot: every argument and return register passes through untouched,
            # so the reconstructed headers' return types (several are only known as void) cannot truncate a result.
            defs.append('__attribute__((naked)) %s %s::%s(%s)%s { __asm__("movq __ZTV%d%s@GOTPCREL(%%rip), %%r11\\n\\tjmpq *%d(%%r11)"); }'
                        % (ret, cls, name, params, c, len(base), base, 8 * (2 + idx)))
            used.add(base); n += 1
        h.append('#define NM_TAHOE_FWD_%s \\\n%s' % (cls, ' \\\n'.join(decl_lines) if decl_lines else ''))
    h.append('#define NM_TAHOE_FWD(cls) NM_TAHOE_FWD_##cls')
    h += ['#define NM_TAHOE_FWD_DEFS \\'] + ['%s \\' % x for x in defs] + ['/* %d forwarded slots */' % n]
    h += ['#else', '#define NM_TAHOE_FWD(cls)', '#define NM_TAHOE_FWD_DEFS', '#endif']
    open(os.path.join(HERE, 'tahoe_fwd.h'), 'w').write('\n'.join(h) + '\n')
    print('tahoe_fwd.h: %d forwarded slots over %d base vtables' % (n, len(used)))
if __name__ == '__main__': main(sys.argv[1], sys.argv[2])
