#!/usr/bin/env python3
"""gen_stubs.py — one vendor subclass per family base; every pure virtual still open along the base chain becomes a logging stub.
v1 missed the family's own overrides because its regex did not accept `APPLE_KEXT_OVERRIDE` before the `;`, so it also
   stubbed methods the family implements (getOwningTask → nullptr …). A stub over a real implementation is a silent lie."""
import re
spec = [("NVResource",["IOAccelResource2"]),("NVSysMemory",["IOAccelSysMemory","IOAccelMemory"]),("NVVidMemory",["IOAccelVidMemory","IOAccelMemory"]),
        ("NVSurface",["IOAccelLegacySurface","IOAccelSurface"]),("NVDisplayPipe",["IOAccelLegacyDisplayPipe","IOAccelDisplayPipe"]),
        ("NVGLContext",["IOAccelGLContext2","IOAccelContext2","IOAccelSubmitter2"]),("NV2DContext",["IOAccel2DContext2","IOAccelContext2","IOAccelSubmitter2"]),
        ("NVCLContext",["IOAccelCLContext2","IOAccelContext2","IOAccelSubmitter2"]),("NVVideoContext",["IOAccelVideoContext2","IOAccelContext2","IOAccelSubmitter2"])]
def decls(hdr):
    out=[]
    for l in open("iofam/%s.h"%hdr):
        m=re.match(r"\s*virtual\s+(.+?)\s+([A-Za-z_][A-Za-z0-9_]*)\((.*?)\)(\s*const)?\s*(= 0)?\s*(APPLE_KEXT_OVERRIDE)?\s*;", l)
        if m: out.append((m.group(1).strip(), m.group(2), m.group(3).strip(), m.group(4) or "", bool(m.group(5))))
    return out
code=["// GENERATED by gen_stubs.py: one vendor subclass per family base; every pure virtual left open along the base chain is a logging stub.", "#pragma once"]
code+=['#include "%s.h"'%c[0] for _,c in spec]
n_st=0; per={}
for cls, chain in spec:
    implemented=set(); pending=[]
    for hdr in chain:                       # most-derived first: a non-pure redeclaration closes a base's pure
        for t,n,a,c,p in decls(hdr):
            key=(n,re.sub(r"\s+","",a))
            if not p: implemented.add(key)
            elif key not in implemented and key not in [(x[1],re.sub(r"\s+","",x[2])) for x in pending]: pending.append((t,n,a,c))
    code.append("class %s : public %s {\n    OSDeclareDefaultStructors(%s)\n    NM_TAHOE_FWD(%s)\npublic:" % (cls, chain[0], cls, cls))
    for t,n,a,c in pending:
        args=[x.strip() for x in a.split(",")] if a.strip() else []
        named=", ".join("%s a%d"%(x,i) for i,x in enumerate(args))
        ret = "" if t=="void" else (" return true;" if (t=="bool" and n.startswith(("commit","update"))) else " return false;" if t=="bool" else " return nullptr;" if "*" in t else " return 0;")
        code.append("    %s %s(%s)%s APPLE_KEXT_OVERRIDE { ALOG(\"%s::%s\");%s }" % (t, n, named, c, cls, n, ret)); n_st+=1
    per[cls]=len(pending)
    code.append("};\nOSDefineMetaClassAndStructors(%s, %s)" % (cls, chain[0]))
open("nvaccel_stubs.h","w").write("\n".join(code)+"\n"); print("stubs:", n_st, per)
