// GENERATED by gen_tahoe_fwd.py for the macOS 26 (Tahoe) build. Do not edit.
#pragma once
#ifdef NM_TAHOE
#define NM_TAHOE_FWD_NVResource \
    void pageon(IOAccelEvent* a0, bool a1) override; \
    void pageon(IOAccelEvent* a0, bool a1, unsigned long long a2) override; \
    void pageoff(IOAccelEvent* a0, bool a1, bool* a2) override; \
    uint64_t getMemoryAllocParameter() override;
#define NM_TAHOE_FWD_NVSysMemory \
    uint64_t getLength() const override; \
    uint64_t setTag(unsigned int a0) override; \
    uint64_t getTag() override;
#define NM_TAHOE_FWD_NVVidMemory \
    uint64_t getLength() const override; \
    uint64_t setTag(unsigned int a0) override; \
    uint64_t getTag() override;
#define NM_TAHOE_FWD_NVSurface \
    void set_shape(eIOAccelSurfaceShapeBits a0, unsigned int a1, IOAccelDeviceRegion* a2, unsigned long long a3) override; \
    void set_shape_backing_length_ext(eIOAccelSurfaceShapeBits a0, unsigned int a1, unsigned long long a2, unsigned int a3, unsigned long long a4, IOAccelDeviceRegion* a5, unsigned long long a6) override; \
    void surface_lock_options(eLockType a0, unsigned int a1, IOAccelSurfaceInformation* a2, unsigned long long a3) override; \
    void surface_unlock_options(eLockType a0, unsigned int a1) override; \
    void submitCopyForward(IOAccelEvent* a0, unsigned int a1, IOAccelResource2* a2, IOAccelResource2* a3, IOAccelBounds const* a4, unsigned int a5) override; \
    void submitUpdate(unsigned int a0, IOAccelBounds* a1, unsigned int a2) override;
#define NM_TAHOE_FWD_NVDisplayPipe \
    void setStereo(IOAccelStereoMode a0) override;
#define NM_TAHOE_FWD_NVGLContext \
    void * getOwningTask() const override; \
    void * getGPUTask() const override; \
    void getOwningTaskPid() const override; \
    void retireCommandBuffer(IOAccelEventFence* a0) override; \
    void setSubmissionError(unsigned int a0) override; \
    bool isOpportunisticWorkload() const override; \
    void postTokenSanityCheck(IOAccelCommandStreamInfo& a0) override; \
    void getDataBufferPrivate(IOAccelResource2* a0, IOAccelResourcePrivate* a1, unsigned long long a2) override; \
    void validateDataBuffer(unsigned long long a0, IOBufferMemoryDescriptor* a1, IOAccelResource2* a2) override; \
    void invalidate() override; \
    void getFrameDelimiter() override; \
    void processSwap(eDoSwap a0) override;
#define NM_TAHOE_FWD_NV2DContext \
    void * getOwningTask() const override; \
    void * getGPUTask() const override; \
    void getOwningTaskPid() const override; \
    void retireCommandBuffer(IOAccelEventFence* a0) override; \
    void setSubmissionError(unsigned int a0) override; \
    bool isOpportunisticWorkload() const override; \
    void postTokenSanityCheck(IOAccelCommandStreamInfo& a0) override; \
    void getDataBufferPrivate(IOAccelResource2* a0, IOAccelResourcePrivate* a1, unsigned long long a2) override; \
    void validateDataBuffer(unsigned long long a0, IOBufferMemoryDescriptor* a1, IOAccelResource2* a2) override; \
    void invalidate() override; \
    void getFrameDelimiter() override;
#define NM_TAHOE_FWD_NVCLContext \
    void * getOwningTask() const override; \
    void * getGPUTask() const override; \
    void getOwningTaskPid() const override; \
    void retireCommandBuffer(IOAccelEventFence* a0) override; \
    void setSubmissionError(unsigned int a0) override; \
    bool isOpportunisticWorkload() const override; \
    void postTokenSanityCheck(IOAccelCommandStreamInfo& a0) override; \
    void getDataBufferPrivate(IOAccelResource2* a0, IOAccelResourcePrivate* a1, unsigned long long a2) override; \
    void validateDataBuffer(unsigned long long a0, IOBufferMemoryDescriptor* a1, IOAccelResource2* a2) override; \
    void invalidate() override; \
    void getFrameDelimiter() override;
#define NM_TAHOE_FWD_NVVideoContext \
    void * getOwningTask() const override; \
    void * getGPUTask() const override; \
    void getOwningTaskPid() const override; \
    void retireCommandBuffer(IOAccelEventFence* a0) override; \
    void setSubmissionError(unsigned int a0) override; \
    bool isOpportunisticWorkload() const override; \
    void postTokenSanityCheck(IOAccelCommandStreamInfo& a0) override; \
    void getDataBufferPrivate(IOAccelResource2* a0, IOAccelResourcePrivate* a1, unsigned long long a2) override; \
    void validateDataBuffer(unsigned long long a0, IOBufferMemoryDescriptor* a1, IOAccelResource2* a2) override; \
    void invalidate() override; \
    void getFrameDelimiter() override;
#define NM_TAHOE_FWD_NVEventMachine \
    void collectAllLiveEventIfNeeded() override;
#define NM_TAHOE_FWD_NVDisplayMachine \
    void setStereo(unsigned int a0, IOAccelStereoMode a1) override;
#define NM_TAHOE_FWD_NVTask \

#define NM_TAHOE_FWD_NVMemoryMap \
    bool matchOptionBits(unsigned int a0) override; \
    unsigned long long getLength() const override;
#define NM_TAHOE_FWD_NVAccel \
    uint64_t tmpTotalVRAM() override; \
    uint64_t totalTextureMemory() override;
#define NM_TAHOE_FWD(cls) NM_TAHOE_FWD_##cls
#define NM_TAHOE_FWD_DEFS \
__attribute__((naked)) void NVResource::pageon(IOAccelEvent* a0, bool a1) { __asm__("movq __ZTV16IOAccelResource2@GOTPCREL(%rip), %r11\n\tjmpq *448(%r11)"); } \
__attribute__((naked)) void NVResource::pageon(IOAccelEvent* a0, bool a1, unsigned long long a2) { __asm__("movq __ZTV16IOAccelResource2@GOTPCREL(%rip), %r11\n\tjmpq *456(%r11)"); } \
__attribute__((naked)) void NVResource::pageoff(IOAccelEvent* a0, bool a1, bool* a2) { __asm__("movq __ZTV16IOAccelResource2@GOTPCREL(%rip), %r11\n\tjmpq *464(%r11)"); } \
__attribute__((naked)) uint64_t NVResource::getMemoryAllocParameter() { __asm__("movq __ZTV16IOAccelResource2@GOTPCREL(%rip), %r11\n\tjmpq *488(%r11)"); } \
__attribute__((naked)) uint64_t NVSysMemory::getLength() const { __asm__("movq __ZTV16IOAccelSysMemory@GOTPCREL(%rip), %r11\n\tjmpq *304(%r11)"); } \
__attribute__((naked)) uint64_t NVSysMemory::setTag(unsigned int a0) { __asm__("movq __ZTV16IOAccelSysMemory@GOTPCREL(%rip), %r11\n\tjmpq *376(%r11)"); } \
__attribute__((naked)) uint64_t NVSysMemory::getTag() { __asm__("movq __ZTV16IOAccelSysMemory@GOTPCREL(%rip), %r11\n\tjmpq *384(%r11)"); } \
__attribute__((naked)) uint64_t NVVidMemory::getLength() const { __asm__("movq __ZTV16IOAccelVidMemory@GOTPCREL(%rip), %r11\n\tjmpq *304(%r11)"); } \
__attribute__((naked)) uint64_t NVVidMemory::setTag(unsigned int a0) { __asm__("movq __ZTV16IOAccelVidMemory@GOTPCREL(%rip), %r11\n\tjmpq *376(%r11)"); } \
__attribute__((naked)) uint64_t NVVidMemory::getTag() { __asm__("movq __ZTV16IOAccelVidMemory@GOTPCREL(%rip), %r11\n\tjmpq *384(%r11)"); } \
__attribute__((naked)) void NVSurface::set_shape(eIOAccelSurfaceShapeBits a0, unsigned int a1, IOAccelDeviceRegion* a2, unsigned long long a3) { __asm__("movq __ZTV20IOAccelLegacySurface@GOTPCREL(%rip), %r11\n\tjmpq *2592(%r11)"); } \
__attribute__((naked)) void NVSurface::set_shape_backing_length_ext(eIOAccelSurfaceShapeBits a0, unsigned int a1, unsigned long long a2, unsigned int a3, unsigned long long a4, IOAccelDeviceRegion* a5, unsigned long long a6) { __asm__("movq __ZTV20IOAccelLegacySurface@GOTPCREL(%rip), %r11\n\tjmpq *2600(%r11)"); } \
__attribute__((naked)) void NVSurface::surface_lock_options(eLockType a0, unsigned int a1, IOAccelSurfaceInformation* a2, unsigned long long a3) { __asm__("movq __ZTV20IOAccelLegacySurface@GOTPCREL(%rip), %r11\n\tjmpq *2608(%r11)"); } \
__attribute__((naked)) void NVSurface::surface_unlock_options(eLockType a0, unsigned int a1) { __asm__("movq __ZTV20IOAccelLegacySurface@GOTPCREL(%rip), %r11\n\tjmpq *2616(%r11)"); } \
__attribute__((naked)) void NVSurface::submitCopyForward(IOAccelEvent* a0, unsigned int a1, IOAccelResource2* a2, IOAccelResource2* a3, IOAccelBounds const* a4, unsigned int a5) { __asm__("movq __ZTV20IOAccelLegacySurface@GOTPCREL(%rip), %r11\n\tjmpq *2656(%r11)"); } \
__attribute__((naked)) void NVSurface::submitUpdate(unsigned int a0, IOAccelBounds* a1, unsigned int a2) { __asm__("movq __ZTV20IOAccelLegacySurface@GOTPCREL(%rip), %r11\n\tjmpq *2664(%r11)"); } \
__attribute__((naked)) void NVDisplayPipe::setStereo(IOAccelStereoMode a0) { __asm__("movq __ZTV24IOAccelLegacyDisplayPipe@GOTPCREL(%rip), %r11\n\tjmpq *2480(%r11)"); } \
__attribute__((naked)) void * NVGLContext::getOwningTask() const { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2416(%r11)"); } \
__attribute__((naked)) void * NVGLContext::getGPUTask() const { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2424(%r11)"); } \
__attribute__((naked)) void NVGLContext::getOwningTaskPid() const { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2432(%r11)"); } \
__attribute__((naked)) void NVGLContext::retireCommandBuffer(IOAccelEventFence* a0) { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2448(%r11)"); } \
__attribute__((naked)) void NVGLContext::setSubmissionError(unsigned int a0) { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2480(%r11)"); } \
__attribute__((naked)) bool NVGLContext::isOpportunisticWorkload() const { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2536(%r11)"); } \
__attribute__((naked)) void NVGLContext::postTokenSanityCheck(IOAccelCommandStreamInfo& a0) { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2608(%r11)"); } \
__attribute__((naked)) void NVGLContext::getDataBufferPrivate(IOAccelResource2* a0, IOAccelResourcePrivate* a1, unsigned long long a2) { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2696(%r11)"); } \
__attribute__((naked)) void NVGLContext::validateDataBuffer(unsigned long long a0, IOBufferMemoryDescriptor* a1, IOAccelResource2* a2) { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2704(%r11)"); } \
__attribute__((naked)) void NVGLContext::invalidate() { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2744(%r11)"); } \
__attribute__((naked)) void NVGLContext::getFrameDelimiter() { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2752(%r11)"); } \
__attribute__((naked)) void NVGLContext::processSwap(eDoSwap a0) { __asm__("movq __ZTV17IOAccelGLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2944(%r11)"); } \
__attribute__((naked)) void * NV2DContext::getOwningTask() const { __asm__("movq __ZTV17IOAccel2DContext2@GOTPCREL(%rip), %r11\n\tjmpq *2416(%r11)"); } \
__attribute__((naked)) void * NV2DContext::getGPUTask() const { __asm__("movq __ZTV17IOAccel2DContext2@GOTPCREL(%rip), %r11\n\tjmpq *2424(%r11)"); } \
__attribute__((naked)) void NV2DContext::getOwningTaskPid() const { __asm__("movq __ZTV17IOAccel2DContext2@GOTPCREL(%rip), %r11\n\tjmpq *2432(%r11)"); } \
__attribute__((naked)) void NV2DContext::retireCommandBuffer(IOAccelEventFence* a0) { __asm__("movq __ZTV17IOAccel2DContext2@GOTPCREL(%rip), %r11\n\tjmpq *2448(%r11)"); } \
__attribute__((naked)) void NV2DContext::setSubmissionError(unsigned int a0) { __asm__("movq __ZTV17IOAccel2DContext2@GOTPCREL(%rip), %r11\n\tjmpq *2480(%r11)"); } \
__attribute__((naked)) bool NV2DContext::isOpportunisticWorkload() const { __asm__("movq __ZTV17IOAccel2DContext2@GOTPCREL(%rip), %r11\n\tjmpq *2536(%r11)"); } \
__attribute__((naked)) void NV2DContext::postTokenSanityCheck(IOAccelCommandStreamInfo& a0) { __asm__("movq __ZTV17IOAccel2DContext2@GOTPCREL(%rip), %r11\n\tjmpq *2608(%r11)"); } \
__attribute__((naked)) void NV2DContext::getDataBufferPrivate(IOAccelResource2* a0, IOAccelResourcePrivate* a1, unsigned long long a2) { __asm__("movq __ZTV17IOAccel2DContext2@GOTPCREL(%rip), %r11\n\tjmpq *2696(%r11)"); } \
__attribute__((naked)) void NV2DContext::validateDataBuffer(unsigned long long a0, IOBufferMemoryDescriptor* a1, IOAccelResource2* a2) { __asm__("movq __ZTV17IOAccel2DContext2@GOTPCREL(%rip), %r11\n\tjmpq *2704(%r11)"); } \
__attribute__((naked)) void NV2DContext::invalidate() { __asm__("movq __ZTV17IOAccel2DContext2@GOTPCREL(%rip), %r11\n\tjmpq *2744(%r11)"); } \
__attribute__((naked)) void NV2DContext::getFrameDelimiter() { __asm__("movq __ZTV17IOAccel2DContext2@GOTPCREL(%rip), %r11\n\tjmpq *2752(%r11)"); } \
__attribute__((naked)) void * NVCLContext::getOwningTask() const { __asm__("movq __ZTV17IOAccelCLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2416(%r11)"); } \
__attribute__((naked)) void * NVCLContext::getGPUTask() const { __asm__("movq __ZTV17IOAccelCLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2424(%r11)"); } \
__attribute__((naked)) void NVCLContext::getOwningTaskPid() const { __asm__("movq __ZTV17IOAccelCLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2432(%r11)"); } \
__attribute__((naked)) void NVCLContext::retireCommandBuffer(IOAccelEventFence* a0) { __asm__("movq __ZTV17IOAccelCLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2448(%r11)"); } \
__attribute__((naked)) void NVCLContext::setSubmissionError(unsigned int a0) { __asm__("movq __ZTV17IOAccelCLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2480(%r11)"); } \
__attribute__((naked)) bool NVCLContext::isOpportunisticWorkload() const { __asm__("movq __ZTV17IOAccelCLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2536(%r11)"); } \
__attribute__((naked)) void NVCLContext::postTokenSanityCheck(IOAccelCommandStreamInfo& a0) { __asm__("movq __ZTV17IOAccelCLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2608(%r11)"); } \
__attribute__((naked)) void NVCLContext::getDataBufferPrivate(IOAccelResource2* a0, IOAccelResourcePrivate* a1, unsigned long long a2) { __asm__("movq __ZTV17IOAccelCLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2696(%r11)"); } \
__attribute__((naked)) void NVCLContext::validateDataBuffer(unsigned long long a0, IOBufferMemoryDescriptor* a1, IOAccelResource2* a2) { __asm__("movq __ZTV17IOAccelCLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2704(%r11)"); } \
__attribute__((naked)) void NVCLContext::invalidate() { __asm__("movq __ZTV17IOAccelCLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2744(%r11)"); } \
__attribute__((naked)) void NVCLContext::getFrameDelimiter() { __asm__("movq __ZTV17IOAccelCLContext2@GOTPCREL(%rip), %r11\n\tjmpq *2752(%r11)"); } \
__attribute__((naked)) void * NVVideoContext::getOwningTask() const { __asm__("movq __ZTV20IOAccelVideoContext2@GOTPCREL(%rip), %r11\n\tjmpq *2416(%r11)"); } \
__attribute__((naked)) void * NVVideoContext::getGPUTask() const { __asm__("movq __ZTV20IOAccelVideoContext2@GOTPCREL(%rip), %r11\n\tjmpq *2424(%r11)"); } \
__attribute__((naked)) void NVVideoContext::getOwningTaskPid() const { __asm__("movq __ZTV20IOAccelVideoContext2@GOTPCREL(%rip), %r11\n\tjmpq *2432(%r11)"); } \
__attribute__((naked)) void NVVideoContext::retireCommandBuffer(IOAccelEventFence* a0) { __asm__("movq __ZTV20IOAccelVideoContext2@GOTPCREL(%rip), %r11\n\tjmpq *2448(%r11)"); } \
__attribute__((naked)) void NVVideoContext::setSubmissionError(unsigned int a0) { __asm__("movq __ZTV20IOAccelVideoContext2@GOTPCREL(%rip), %r11\n\tjmpq *2480(%r11)"); } \
__attribute__((naked)) bool NVVideoContext::isOpportunisticWorkload() const { __asm__("movq __ZTV20IOAccelVideoContext2@GOTPCREL(%rip), %r11\n\tjmpq *2536(%r11)"); } \
__attribute__((naked)) void NVVideoContext::postTokenSanityCheck(IOAccelCommandStreamInfo& a0) { __asm__("movq __ZTV20IOAccelVideoContext2@GOTPCREL(%rip), %r11\n\tjmpq *2608(%r11)"); } \
__attribute__((naked)) void NVVideoContext::getDataBufferPrivate(IOAccelResource2* a0, IOAccelResourcePrivate* a1, unsigned long long a2) { __asm__("movq __ZTV20IOAccelVideoContext2@GOTPCREL(%rip), %r11\n\tjmpq *2696(%r11)"); } \
__attribute__((naked)) void NVVideoContext::validateDataBuffer(unsigned long long a0, IOBufferMemoryDescriptor* a1, IOAccelResource2* a2) { __asm__("movq __ZTV20IOAccelVideoContext2@GOTPCREL(%rip), %r11\n\tjmpq *2704(%r11)"); } \
__attribute__((naked)) void NVVideoContext::invalidate() { __asm__("movq __ZTV20IOAccelVideoContext2@GOTPCREL(%rip), %r11\n\tjmpq *2744(%r11)"); } \
__attribute__((naked)) void NVVideoContext::getFrameDelimiter() { __asm__("movq __ZTV20IOAccelVideoContext2@GOTPCREL(%rip), %r11\n\tjmpq *2752(%r11)"); } \
__attribute__((naked)) void NVEventMachine::collectAllLiveEventIfNeeded() { __asm__("movq __ZTV24IOAccelEventMachineFast2@GOTPCREL(%rip), %r11\n\tjmpq *576(%r11)"); } \
__attribute__((naked)) void NVDisplayMachine::setStereo(unsigned int a0, IOAccelStereoMode a1) { __asm__("movq __ZTV27IOAccelLegacyDisplayMachine@GOTPCREL(%rip), %r11\n\tjmpq *2304(%r11)"); } \
__attribute__((naked)) bool NVMemoryMap::matchOptionBits(unsigned int a0) { __asm__("movq __ZTV16IOAccelMemoryMap@GOTPCREL(%rip), %r11\n\tjmpq *304(%r11)"); } \
__attribute__((naked)) unsigned long long NVMemoryMap::getLength() const { __asm__("movq __ZTV16IOAccelMemoryMap@GOTPCREL(%rip), %r11\n\tjmpq *376(%r11)"); } \
__attribute__((naked)) uint64_t NVAccel::tmpTotalVRAM() { __asm__("movq __ZTV22IOGraphicsAccelerator2@GOTPCREL(%rip), %r11\n\tjmpq *2160(%r11)"); } \
__attribute__((naked)) uint64_t NVAccel::totalTextureMemory() { __asm__("movq __ZTV22IOGraphicsAccelerator2@GOTPCREL(%rip), %r11\n\tjmpq *2168(%r11)"); } \
/* 68 forwarded slots */
#else
#define NM_TAHOE_FWD(cls)
#define NM_TAHOE_FWD_DEFS
#endif
